import React from "react";
import SideMenu from "../SideMenu/SideMenu";
import { useSession } from "next-auth/react";
import scss from "./Layout.module.scss";
import Head from "next/head";
import Footer from "../Footer/Footer";
const Layout = (props: any) => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={scss.layout}
        style={{ padding: session ? "70px 24px 0 80px" : 0}}
      >
        {session && <SideMenu/>}
        {session && props.children}
      </main>
    </>
  );
};

export default Layout;
